Question {
    shape: "class"

    - question: String
    - answers: "String[0..*]"
    - solution: "Integer"

    + Question(question, answers, solutions)
    + getQuestion(): String
    + getAnswers(): "String[0..*]"
    + getSolutions(): "Integer[0..*]"
    + setQuestion(question\: String)
    + setAnswers(answers\: String\[0\.\.\*\])
    + setSolutions(solutions\: String\[0\.\.\*\])

    - isValidReference(reference\: Integer): Boolean
}