JSONQuestionExtractor {
    shape: class
    + read(path\: String): "Question[0..*]"
}

Question : @../Question/Question.Question

noteFiles : |md
    `File` represents the programming language specific
    class which handles file management
|

noteFiles -- JSONQuestionExtractor

JSONQuestionExtractor -> Question: «create» {
    style: {
        stroke-dash: 3
    }
}