JSONQuestionExtractor {
    shape: class
    + read(path\: String): "Question[0..*]"
    - checkPath(path\: String)
    - checkFormatting(file\: File)
    - checkContent(properly_formatted_file\: File)
    - parseQuestion(file\: File): "Question[0..1]"
}

Question : @../Question/Question.Question

noteFiles : |md
    `File` represents the programming language specific
    class which handles file management
|

noteFiles -- JSONQuestionExtractor

JSONQuestionExtractor -> Question: «create» {
    style: {
        stroke-dash: 3
    }
}